### ISSUE TITLE
[HELP] Some settings are not working and I'd like some help, thanks!

### ISSUE THREAD

**Issue by maaxxicarvalho** [ByteInternet/hypernode-docker#30]
Hello,

I'm configuring the `hypernode-docker` with docker-compose for my local development.

* I'm running on a Macos machine with all latest software installed (OSX, Docker for Mac).
* I'm running Magento 1.
* To access the Docker container I'm simply using `docker-compose exec -u app app bash` and not the SSH as per Hypernode instructions. I don't know if there's any difference.

Here's my `docker-compose.yml` file:
```yaml
version: '3'
services:
  app:
    build:
      context: docker/images/hypernode
      dockerfile: Dockerfile
    image: smoke/hypernode
    volumes:
      - '.:/data/web/public/:cached'
      - 'hypernode-db:/data/mysql/:cached'
    working_dir: /data/web/
    ports:
      - '80:80'
      - '222:22'
      - '443:443'
      - '3306:3306'
volumes:
  hypernode-db:
    driver: local
```

You can see that I'm using a custom `Dockerfile`.
That's because I found that the easier way to have some of the configurations I need to be persisted into the codebase.

Here's the `Dockerfile`
```
FROM docker.hypernode.com/byteinternet/hypernode-docker:latest

COPY 60_restart_services.sh /etc/my_init.d/60_restart_services.sh
COPY outside.conf /etc/nginx/outside.conf

RUN echo "app     ALL = (ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN apt-get update && apt-get install -y php-xdebug && chmod +x /etc/my_init.d/60_restart_services.sh
```

### To enable PHP 7.2 I changed the `60_restart_services.sh`, here are the changed lines:
```bash
/usr/bin/screen -S hypernode_service_php -d -m /usr/sbin/php-fpm7.2 --nodaemonize --fpm-config /etc/php/7.2/fpm/php-fpm.conf
update-alternatives --set php $(which php7.2)
```

### To enable Varnish
I followed the instructions from here [Hypernode Docker - Varnish on Docker](https://support.hypernode.com/knowledgebase/hypernode-docker/#Varnish_on_Docker)

### Varnish is not working
Once I applied the changes necessary to make Varnish run the frontend stopped working and I'm getting a 500 error.

I cannot apply the Varnish configurations on the admin panel (*System* > *Cache Management* > *Apply Varnish Config*). I'm getting the following error:

```
Error determining Varnish version: Got unexpected response code from Varnish: 500
Failed to apply the VCL to 127.0.0.1:6082: Failed to load configurator
```

### `hypernode-systemctl` is not working

I'm getting the following response:

```bash
app@1988ee43035f:~$ hypernode-systemctl
Looks like something went wrong: b'{"detail":"Invalid token."}'
Looks like something went wrong: b'{"detail":"Invalid token."}'
usage: hypernode-systemctl [-h] [--verbose]
                           {settings,whitelist,block_attack,attach_backup} ...

positional arguments:
  {settings,whitelist,block_attack,attach_backup}

optional arguments:
  -h, --help            show this help message and exit
  --verbose, -v         Display debug output
```

Thank you very much for your help.
